package kanta.test;
// Generated by ComTest BEGIN

import kanta.*;
import org.junit.*;

import static org.junit.Assert.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.03.31 16:30:08 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuvanArpominenTest {



  // Generated by ComTest BEGIN
  /** testTarkistaTupa42 */
  @Test
  public void testTarkistaTupa42() {    // TuvanArpominen: 42
    TuvanArpominen tuvanTarkistus = new TuvanArpominen(); 
    assertEquals("From: TuvanArpominen line: 44", null, tuvanTarkistus.tarkistaTupa("Rohkelikko")); 
    assertEquals("From: TuvanArpominen line: 45", "Väärä tupa", tuvanTarkistus.tarkistaTupa("Rohkea Rohkelikko")); 
    assertEquals("From: TuvanArpominen line: 46", null, tuvanTarkistus.tarkistaTupa("Luihuinen")); 
  } // Generated by ComTest END
}